name: Run Tests

on:
  push:
    branches: [ master, v2 ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: arduino/arduino-lint-action
      uses: arduino/arduino-lint-action@v1.0.0
      with:
        library-manager: update
    - name: run tests
      run: |
        cd tests
        make test
    - name: compile example
      run: |
        cd tests
        make example
